/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedTimeOffRouteImport } from './routes/_authenticated/time-off'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated/sops'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyJobsRouteImport } from './routes/_authenticated/my-jobs'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin.index'
import { Route as AuthenticatedSuperAdminAuditRouteImport } from './routes/_authenticated/super-admin.audit'
import { Route as AuthenticatedSettingsVoiceRouteImport } from './routes/_authenticated/settings.voice'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsBusinessRouteImport } from './routes/_authenticated/settings.business'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedInventoryUsageRouteImport } from './routes/_authenticated/inventory.usage'
import { Route as AuthenticatedInventoryRecipesRouteImport } from './routes/_authenticated/inventory.recipes'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedSuperAdminTenantsTenantIdRouteImport } from './routes/_authenticated/super-admin.tenants.$tenantId'
import { Route as ApiPublicHooksTurnoTenantIdRouteImport } from './routes/api/public/hooks/turno.$tenantId'
import { Route as ApiPublicHooksLeadTenantIdRouteImport } from './routes/api/public/hooks/lead.$tenantId'
import { Route as ApiPublicTwilioVoiceTenantIdStatusRouteImport } from './routes/api/public/twilio/voice.$tenantId.status'
import { Route as ApiPublicTwilioVoiceTenantIdIncomingRouteImport } from './routes/api/public/twilio/voice.$tenantId.incoming'
import { Route as ApiPublicTwilioVoiceTenantIdGatherRouteImport } from './routes/api/public/twilio/voice.$tenantId.gather'
import { Route as ApiPublicTwilioSmsTenantIdStatusRouteImport } from './routes/api/public/twilio/sms.$tenantId.status'
import { Route as ApiPublicTwilioSmsTenantIdIncomingRouteImport } from './routes/api/public/twilio/sms.$tenantId.incoming'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeOffRoute = AuthenticatedTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyJobsRoute = AuthenticatedMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAuditRoute =
  AuthenticatedSuperAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSettingsVoiceRoute =
  AuthenticatedSettingsVoiceRouteImport.update({
    id: '/settings/voice',
    path: '/settings/voice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBusinessRoute =
  AuthenticatedSettingsBusinessRouteImport.update({
    id: '/settings/business',
    path: '/settings/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInventoryUsageRoute =
  AuthenticatedInventoryUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryRecipesRoute =
  AuthenticatedInventoryRecipesRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminTenantsTenantIdRoute =
  AuthenticatedSuperAdminTenantsTenantIdRouteImport.update({
    id: '/tenants/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const ApiPublicHooksTurnoTenantIdRoute =
  ApiPublicHooksTurnoTenantIdRouteImport.update({
    id: '/api/public/hooks/turno/$tenantId',
    path: '/api/public/hooks/turno/$tenantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadTenantIdRoute =
  ApiPublicHooksLeadTenantIdRouteImport.update({
    id: '/api/public/hooks/lead/$tenantId',
    path: '/api/public/hooks/lead/$tenantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceTenantIdStatusRoute =
  ApiPublicTwilioVoiceTenantIdStatusRouteImport.update({
    id: '/api/public/twilio/voice/$tenantId/status',
    path: '/api/public/twilio/voice/$tenantId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceTenantIdIncomingRoute =
  ApiPublicTwilioVoiceTenantIdIncomingRouteImport.update({
    id: '/api/public/twilio/voice/$tenantId/incoming',
    path: '/api/public/twilio/voice/$tenantId/incoming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceTenantIdGatherRoute =
  ApiPublicTwilioVoiceTenantIdGatherRouteImport.update({
    id: '/api/public/twilio/voice/$tenantId/gather',
    path: '/api/public/twilio/voice/$tenantId/gather',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioSmsTenantIdStatusRoute =
  ApiPublicTwilioSmsTenantIdStatusRouteImport.update({
    id: '/api/public/twilio/sms/$tenantId/status',
    path: '/api/public/twilio/sms/$tenantId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioSmsTenantIdIncomingRoute =
  ApiPublicTwilioSmsTenantIdIncomingRouteImport.update({
    id: '/api/public/twilio/sms/$tenantId/incoming',
    path: '/api/public/twilio/sms/$tenantId/incoming',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/time-off': typeof AuthenticatedTimeOffRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pay/return': typeof PayReturnRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/inventory/recipes': typeof AuthenticatedInventoryRecipesRoute
  '/inventory/usage': typeof AuthenticatedInventoryUsageRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/super-admin/tenants/$tenantId': typeof AuthenticatedSuperAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/hooks/lead/$tenantId': typeof ApiPublicHooksLeadTenantIdRoute
  '/api/public/hooks/turno/$tenantId': typeof ApiPublicHooksTurnoTenantIdRoute
  '/api/public/twilio/sms/$tenantId/incoming': typeof ApiPublicTwilioSmsTenantIdIncomingRoute
  '/api/public/twilio/sms/$tenantId/status': typeof ApiPublicTwilioSmsTenantIdStatusRoute
  '/api/public/twilio/voice/$tenantId/gather': typeof ApiPublicTwilioVoiceTenantIdGatherRoute
  '/api/public/twilio/voice/$tenantId/incoming': typeof ApiPublicTwilioVoiceTenantIdIncomingRoute
  '/api/public/twilio/voice/$tenantId/status': typeof ApiPublicTwilioVoiceTenantIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/time-off': typeof AuthenticatedTimeOffRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pay/return': typeof PayReturnRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/inventory/recipes': typeof AuthenticatedInventoryRecipesRoute
  '/inventory/usage': typeof AuthenticatedInventoryUsageRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/super-admin/tenants/$tenantId': typeof AuthenticatedSuperAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/hooks/lead/$tenantId': typeof ApiPublicHooksLeadTenantIdRoute
  '/api/public/hooks/turno/$tenantId': typeof ApiPublicHooksTurnoTenantIdRoute
  '/api/public/twilio/sms/$tenantId/incoming': typeof ApiPublicTwilioSmsTenantIdIncomingRoute
  '/api/public/twilio/sms/$tenantId/status': typeof ApiPublicTwilioSmsTenantIdStatusRoute
  '/api/public/twilio/voice/$tenantId/gather': typeof ApiPublicTwilioVoiceTenantIdGatherRoute
  '/api/public/twilio/voice/$tenantId/incoming': typeof ApiPublicTwilioVoiceTenantIdIncomingRoute
  '/api/public/twilio/voice/$tenantId/status': typeof ApiPublicTwilioVoiceTenantIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-jobs': typeof AuthenticatedMyJobsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/sops': typeof AuthenticatedSopsRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/time-off': typeof AuthenticatedTimeOffRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pay/return': typeof PayReturnRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/inventory/recipes': typeof AuthenticatedInventoryRecipesRoute
  '/_authenticated/inventory/usage': typeof AuthenticatedInventoryUsageRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/_authenticated/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/_authenticated/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/super-admin/tenants/$tenantId': typeof AuthenticatedSuperAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/hooks/lead/$tenantId': typeof ApiPublicHooksLeadTenantIdRoute
  '/api/public/hooks/turno/$tenantId': typeof ApiPublicHooksTurnoTenantIdRoute
  '/api/public/twilio/sms/$tenantId/incoming': typeof ApiPublicTwilioSmsTenantIdIncomingRoute
  '/api/public/twilio/sms/$tenantId/status': typeof ApiPublicTwilioSmsTenantIdStatusRoute
  '/api/public/twilio/voice/$tenantId/gather': typeof ApiPublicTwilioVoiceTenantIdGatherRoute
  '/api/public/twilio/voice/$tenantId/incoming': typeof ApiPublicTwilioVoiceTenantIdIncomingRoute
  '/api/public/twilio/voice/$tenantId/status': typeof ApiPublicTwilioVoiceTenantIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/messages'
    | '/my-jobs'
    | '/onboarding'
    | '/reports'
    | '/requests'
    | '/services'
    | '/sops'
    | '/super-admin'
    | '/team'
    | '/time-off'
    | '/voice'
    | '/pay/$invoiceId'
    | '/pay/return'
    | '/clients/$clientId'
    | '/inventory/recipes'
    | '/inventory/usage'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/leads/$leadId'
    | '/settings/ai'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/templates'
    | '/settings/voice'
    | '/super-admin/audit'
    | '/super-admin/'
    | '/super-admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/api/public/hooks/lead/$tenantId'
    | '/api/public/hooks/turno/$tenantId'
    | '/api/public/twilio/sms/$tenantId/incoming'
    | '/api/public/twilio/sms/$tenantId/status'
    | '/api/public/twilio/voice/$tenantId/gather'
    | '/api/public/twilio/voice/$tenantId/incoming'
    | '/api/public/twilio/voice/$tenantId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/messages'
    | '/my-jobs'
    | '/onboarding'
    | '/reports'
    | '/requests'
    | '/services'
    | '/sops'
    | '/team'
    | '/time-off'
    | '/voice'
    | '/pay/$invoiceId'
    | '/pay/return'
    | '/clients/$clientId'
    | '/inventory/recipes'
    | '/inventory/usage'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/leads/$leadId'
    | '/settings/ai'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/templates'
    | '/settings/voice'
    | '/super-admin/audit'
    | '/super-admin'
    | '/super-admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/api/public/hooks/lead/$tenantId'
    | '/api/public/hooks/turno/$tenantId'
    | '/api/public/twilio/sms/$tenantId/incoming'
    | '/api/public/twilio/sms/$tenantId/status'
    | '/api/public/twilio/voice/$tenantId/gather'
    | '/api/public/twilio/voice/$tenantId/incoming'
    | '/api/public/twilio/voice/$tenantId/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/calendar'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/jobs'
    | '/_authenticated/leads'
    | '/_authenticated/messages'
    | '/_authenticated/my-jobs'
    | '/_authenticated/onboarding'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/services'
    | '/_authenticated/sops'
    | '/_authenticated/super-admin'
    | '/_authenticated/team'
    | '/_authenticated/time-off'
    | '/_authenticated/voice'
    | '/pay/$invoiceId'
    | '/pay/return'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/inventory/recipes'
    | '/_authenticated/inventory/usage'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/business'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/templates'
    | '/_authenticated/settings/voice'
    | '/_authenticated/super-admin/audit'
    | '/_authenticated/super-admin/'
    | '/_authenticated/super-admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/api/public/hooks/lead/$tenantId'
    | '/api/public/hooks/turno/$tenantId'
    | '/api/public/twilio/sms/$tenantId/incoming'
    | '/api/public/twilio/sms/$tenantId/status'
    | '/api/public/twilio/voice/$tenantId/gather'
    | '/api/public/twilio/voice/$tenantId/incoming'
    | '/api/public/twilio/voice/$tenantId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
  PayReturnRoute: typeof PayReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicHooksLeadTenantIdRoute: typeof ApiPublicHooksLeadTenantIdRoute
  ApiPublicHooksTurnoTenantIdRoute: typeof ApiPublicHooksTurnoTenantIdRoute
  ApiPublicTwilioSmsTenantIdIncomingRoute: typeof ApiPublicTwilioSmsTenantIdIncomingRoute
  ApiPublicTwilioSmsTenantIdStatusRoute: typeof ApiPublicTwilioSmsTenantIdStatusRoute
  ApiPublicTwilioVoiceTenantIdGatherRoute: typeof ApiPublicTwilioVoiceTenantIdGatherRoute
  ApiPublicTwilioVoiceTenantIdIncomingRoute: typeof ApiPublicTwilioVoiceTenantIdIncomingRoute
  ApiPublicTwilioVoiceTenantIdStatusRoute: typeof ApiPublicTwilioVoiceTenantIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-off': {
      id: '/_authenticated/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof AuthenticatedTimeOffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-jobs': {
      id: '/_authenticated/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof AuthenticatedMyJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/audit': {
      id: '/_authenticated/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/settings/voice': {
      id: '/_authenticated/settings/voice'
      path: '/settings/voice'
      fullPath: '/settings/voice'
      preLoaderRoute: typeof AuthenticatedSettingsVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/business': {
      id: '/_authenticated/settings/business'
      path: '/settings/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/inventory/usage': {
      id: '/_authenticated/inventory/usage'
      path: '/usage'
      fullPath: '/inventory/usage'
      preLoaderRoute: typeof AuthenticatedInventoryUsageRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/recipes': {
      id: '/_authenticated/inventory/recipes'
      path: '/recipes'
      fullPath: '/inventory/recipes'
      preLoaderRoute: typeof AuthenticatedInventoryRecipesRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/tenants/$tenantId': {
      id: '/_authenticated/super-admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/super-admin/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedSuperAdminTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/api/public/hooks/turno/$tenantId': {
      id: '/api/public/hooks/turno/$tenantId'
      path: '/api/public/hooks/turno/$tenantId'
      fullPath: '/api/public/hooks/turno/$tenantId'
      preLoaderRoute: typeof ApiPublicHooksTurnoTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead/$tenantId': {
      id: '/api/public/hooks/lead/$tenantId'
      path: '/api/public/hooks/lead/$tenantId'
      fullPath: '/api/public/hooks/lead/$tenantId'
      preLoaderRoute: typeof ApiPublicHooksLeadTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice/$tenantId/status': {
      id: '/api/public/twilio/voice/$tenantId/status'
      path: '/api/public/twilio/voice/$tenantId/status'
      fullPath: '/api/public/twilio/voice/$tenantId/status'
      preLoaderRoute: typeof ApiPublicTwilioVoiceTenantIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice/$tenantId/incoming': {
      id: '/api/public/twilio/voice/$tenantId/incoming'
      path: '/api/public/twilio/voice/$tenantId/incoming'
      fullPath: '/api/public/twilio/voice/$tenantId/incoming'
      preLoaderRoute: typeof ApiPublicTwilioVoiceTenantIdIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice/$tenantId/gather': {
      id: '/api/public/twilio/voice/$tenantId/gather'
      path: '/api/public/twilio/voice/$tenantId/gather'
      fullPath: '/api/public/twilio/voice/$tenantId/gather'
      preLoaderRoute: typeof ApiPublicTwilioVoiceTenantIdGatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms/$tenantId/status': {
      id: '/api/public/twilio/sms/$tenantId/status'
      path: '/api/public/twilio/sms/$tenantId/status'
      fullPath: '/api/public/twilio/sms/$tenantId/status'
      preLoaderRoute: typeof ApiPublicTwilioSmsTenantIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms/$tenantId/incoming': {
      id: '/api/public/twilio/sms/$tenantId/incoming'
      path: '/api/public/twilio/sms/$tenantId/incoming'
      fullPath: '/api/public/twilio/sms/$tenantId/incoming'
      preLoaderRoute: typeof ApiPublicTwilioSmsTenantIdIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventoryRecipesRoute: typeof AuthenticatedInventoryRecipesRoute
  AuthenticatedInventoryUsageRoute: typeof AuthenticatedInventoryUsageRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventoryRecipesRoute: AuthenticatedInventoryRecipesRoute,
    AuthenticatedInventoryUsageRoute: AuthenticatedInventoryUsageRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAuditRoute: typeof AuthenticatedSuperAdminAuditRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminTenantsTenantIdRoute: typeof AuthenticatedSuperAdminTenantsTenantIdRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAuditRoute: AuthenticatedSuperAdminAuditRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminTenantsTenantIdRoute:
      AuthenticatedSuperAdminTenantsTenantIdRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyJobsRoute: typeof AuthenticatedMyJobsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTimeOffRoute: typeof AuthenticatedTimeOffRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsBusinessRoute: typeof AuthenticatedSettingsBusinessRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
  AuthenticatedSettingsVoiceRoute: typeof AuthenticatedSettingsVoiceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyJobsRoute: AuthenticatedMyJobsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSopsRoute: AuthenticatedSopsRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTimeOffRoute: AuthenticatedTimeOffRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsBusinessRoute: AuthenticatedSettingsBusinessRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
  AuthenticatedSettingsVoiceRoute: AuthenticatedSettingsVoiceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
  PayReturnRoute: PayReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicHooksLeadTenantIdRoute: ApiPublicHooksLeadTenantIdRoute,
  ApiPublicHooksTurnoTenantIdRoute: ApiPublicHooksTurnoTenantIdRoute,
  ApiPublicTwilioSmsTenantIdIncomingRoute:
    ApiPublicTwilioSmsTenantIdIncomingRoute,
  ApiPublicTwilioSmsTenantIdStatusRoute: ApiPublicTwilioSmsTenantIdStatusRoute,
  ApiPublicTwilioVoiceTenantIdGatherRoute:
    ApiPublicTwilioVoiceTenantIdGatherRoute,
  ApiPublicTwilioVoiceTenantIdIncomingRoute:
    ApiPublicTwilioVoiceTenantIdIncomingRoute,
  ApiPublicTwilioVoiceTenantIdStatusRoute:
    ApiPublicTwilioVoiceTenantIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
